spring:
       profiles:
                active: dev
server:
       port: 8099

person1:
       firstName: Joey
       lastName: Qiao
       age: 19
       hobbies: [hobby0, hobby1]
       pets: {tom: cat, jack: dog}
       email: aaa@aa.com

---
spring:
       profiles: dev

server:
       port: 8098

---
spring:
       profiles: prod
server:
       port: 8097
